import { reactive } from 'vue';

export let store = reactive({
    title: 'Japanese Jisho',
    words: false,
    search: ''
});

export let nav = reactive([
    {name: 'Nav', visible: false},
    {name: 'Japanese Jisho', visible: true},
    {name: 'Dictionary', visible: false},
    {name: 'Word lists', visible: false},
    {name: 'Kana table', visible: false},
    {name: 'Kanji table', visible: false},
    {name: 'Settings', visible: false},
]);

export let list = reactive([
    {name: 'l1', visible: false, start: 0, end: 1000},
    {name: 'l2', visible: false, start: 1001, end: 2000},
    {name: 'l3', visible: false, start: 2001, end: 3000},
    {name: 'l4', visible: false, start: 3001, end: 4000},
    {name: 'l5', visible: false, start: 4001, end: 5000},
    {name: 'l6', visible: false, start: 5001, end: 6000},
    {name: 'l7', visible: false, start: 6001, end: 7000},
    {name: 'l8', visible: false, start: 7001, end: 8000},
    {name: 'l9', visible: false, start: 8001, end: 9000},
    {name: 'l10', visible: false, start: 9001, end: 10000},

]);



export let hiragana = reactive([
    {kana: 'あ', romaji: 'a', toggle: false},
    {kana: 'い', romaji: 'i'},
    {kana: 'う', romaji: 'u'},
    {kana: 'え', romaji: 'e'},
    {kana: 'お', romaji: 'o'},
    {kana: 'か', romaji: 'ka'},
    {kana: 'き', romaji: 'ki'},
    {kana: 'く', romaji: 'ku'},
    {kana: 'け', romaji: 'ke'},
    {kana: 'こ', romaji: 'ko'},
    {kana: 'さ', romaji: 'sa'},
    {kana: 'し', romaji: 'shi'},
    {kana: 'す', romaji: 'su'},
    {kana: 'せ', romaji: 'se'},
    {kana: 'そ', romaji: 'so'},
    {kana: 'た', romaji: 'ta'},
    {kana: 'ち', romaji: 'chi'},
    {kana: 'つ', romaji: 'tsu'},
    {kana: 'て', romaji: 'te'},
    {kana: 'と', romaji: 'to'},
    {kana: 'な', romaji: 'na'},
    {kana: 'に', romaji: 'ni'},
    {kana: 'ぬ', romaji: 'nu'},
    {kana: 'ね', romaji: 'ne'},
    {kana: 'の', romaji: 'no'},
    {kana: 'は', romaji: 'ha'},
    {kana: 'ひ', romaji: 'hi'},
    {kana: 'ふ', romaji: 'fu'},
    {kana: 'へ', romaji: 'he'},
    {kana: 'ほ', romaji: 'ho'},
    {kana: 'ま', romaji: 'ma'},
    {kana: 'み', romaji: 'mi'},
    {kana: 'む', romaji: 'mu'},
    {kana: 'め', romaji: 'me'},
    {kana: 'も', romaji: 'mo'},
    {kana: 'や', romaji: 'ya'},
    {kana: 'ゆ', romaji: 'yu'},
    {kana: 'よ', romaji: 'yo'},
    {kana: 'ら', romaji: 'ra'},
    {kana: 'り', romaji: 'ri'},
    {kana: 'る', romaji: 'ru'},
    {kana: 'れ', romaji: 're'},
    {kana: 'ろ', romaji: 'ro'},
    {kana: 'わ', romaji: 'wa'},
    {kana: 'を', romaji: 'wo'},
    {kana: 'ん', romaji: 'n'},
    {kana: 'が', romaji: 'ga'},
    {kana: 'ぎ', romaji: 'gi'},
    {kana: 'ぐ', romaji: 'gu'},
    {kana: 'げ', romaji: 'ge'},
    {kana: 'ご', romaji: 'go'},
    {kana: 'ざ', romaji: 'za'},
    {kana: 'じ', romaji: 'ji'},
    {kana: 'ず', romaji: 'zu'},
    {kana: 'ぜ', romaji: 'ze'},
    {kana: 'ぞ', romaji: 'zo'},
    {kana: 'だ', romaji: 'da'},
    {kana: 'ぢ', romaji: 'di'},
    {kana: 'づ', romaji: 'du'},
    {kana: 'で', romaji: 'de'},
    {kana: 'ど', romaji: 'do'},
    {kana: 'ば', romaji: 'ba'},
    {kana: 'び', romaji: 'bi'},
    {kana: 'ぶ', romaji: 'bu'},
    {kana: 'べ', romaji: 'be'},
    {kana: 'ぼ', romaji: 'bo'},
    {kana: 'ぱ', romaji: 'pa'},
    {kana: 'ぴ', romaji: 'pi'},
    {kana: 'ぷ', romaji: 'pu'},
    {kana: 'ぺ', romaji: 'pe'},
    {kana: 'ぽ', romaji: 'po'},
]);

export let katakana = reactive([
    {kana: 'ア', romaji: 'a'},
    {kana: 'イ', romaji: 'i'},
    {kana: 'ウ', romaji: 'u'},
    {kana: 'エ', romaji: 'e'},
    {kana: 'オ', romaji: 'o'},
    {kana: 'カ', romaji: 'ka'},
    {kana: 'キ', romaji: 'ki'},
    {kana: 'ク', romaji: 'ku'},
    {kana: 'ケ', romaji: 'ke'},
    {kana: 'コ', romaji: 'ko'},
    {kana: 'サ', romaji: 'sa'},
    {kana: 'シ', romaji: 'shi'},
    {kana: 'ス', romaji: 'su'},
    {kana: 'セ', romaji: 'se'},
    {kana: 'ソ', romaji: 'so'},
    {kana: 'タ', romaji: 'ta'},
    {kana: 'チ', romaji: 'chi'},
    {kana: 'ツ', romaji: 'tsu'},
    {kana: 'テ', romaji: 'te'},
    {kana: 'ト', romaji: 'to'},
    {kana: 'ナ', romaji: 'na'},
    {kana: 'ニ', romaji: 'ni'},
    {kana: 'ヌ', romaji: 'nu'},
    {kana: 'ネ', romaji: 'ne'},
    {kana: 'ノ', romaji: 'no'},
    {kana: 'ハ', romaji: 'ha'},
    {kana: 'ヒ', romaji: 'hi'},
    {kana: 'フ', romaji: 'fu'},
    {kana: 'ヘ', romaji: 'he'},
    {kana: 'ホ', romaji: 'ho'},
    {kana: 'マ', romaji: 'ma'},
    {kana: 'ミ', romaji: 'mi'},
    {kana: 'ム', romaji: 'mu'},
    {kana: 'メ', romaji: 'me'},
    {kana: 'モ', romaji: 'mo'},
    {kana: 'ヤ', romaji: 'ya'},
    {kana: 'ユ', romaji: 'yu'},
    {kana: 'ヨ', romaji: 'yo'},
    {kana: 'ラ', romaji: 'ra'},
    {kana: 'リ', romaji: 'ri'},
    {kana: 'ル', romaji: 'ru'},
    {kana: 'レ', romaji: 're'},
    {kana: 'ロ', romaji: 'ro'},
    {kana: 'ワ', romaji: 'wa'},
    {kana: 'ヲ', romaji: 'wo'},
    {kana: 'ン', romaji: 'n'},
    {kana: 'ガ', romaji: 'ga'},
    {kana: 'ギ', romaji: 'gi'},
    {kana: 'グ', romaji: 'gu'},
    {kana: 'ゲ', romaji: 'ge'},
    {kana: 'ゴ', romaji: 'go'},
    {kana: 'ザ', romaji: 'za'},
    {kana: 'ジ', romaji: 'ji'},
    {kana: 'ズ', romaji: 'zu'},
    {kana: 'ゼ', romaji: 'ze'},
    {kana: 'ゾ', romaji: 'zo'},
    {kana: 'ダ', romaji: 'da'},
    {kana: 'ヂ', romaji: 'di'},
    {kana: 'ヅ', romaji: 'du'},
    {kana: 'デ', romaji: 'de'},
    {kana: 'ド', romaji: 'do'},
    {kana: 'バ', romaji: 'ba'},
    {kana: 'ビ', romaji: 'bi'},
    {kana: 'ブ', romaji: 'bu'},
    {kana: 'ベ', romaji: 'be'},
    {kana: 'ボ', romaji: 'bo'},
    {kana: 'パ', romaji: 'pa'},
    {kana: 'ピ', romaji: 'pi'},
    {kana: 'プ', romaji: 'pu'},
    {kana: 'ペ', romaji: 'pe'},
    {kana: 'ポ', romaji: 'po'},
]);


